accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("<int:id>/profile/", views.profile, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path("update_nickname/", views.update_nickname, name="update_nickname"),
    path("<int:id>/follow/", views.follow, name="follow"),
    path('<int:id>/like_article/', views.like_article, name='like_article'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('article/<int:id>/', views.article, name='article'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('<int:id>/like/', views.like, name='like'),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.


class User(AbstractUser):
    nickname = models.CharField(max_length=100, null=True, blank=False)
    followings = models.ManyToManyField('self', symmetrical=False ,related_name="followers")

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm, PasswordChangeForm, PasswordChangeForm, ReadOnlyPasswordHashField, ReadOnlyPasswordHashWidget, UsernameField
from django.contrib.auth import get_user_model, password_validation
from django.utils.translation import gettext_lazy as _
from django.utils.translation import ngettext, gettext
from django.contrib.auth.password_validation import MinimumLengthValidator, UserAttributeSimilarityValidator, CommonPasswordValidator, NumericPasswordValidator, exceeds_maximum_length_ratio, SequenceMatcher
from django import forms
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, identify_hasher
from django.core.exceptions import ValidationError, FieldDoesNotExist
import re


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        "invalid_login": _(
            "아이디와 비밀번호를 확인해주세요."
        ),
        "inactive": _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password'].help_text = ''
        self.fields['username'].label = ''
        self.fields['password'].label = ''
        self.fields['username'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['password'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['username'].widget.attrs['placeholder'] = '아이디'
        self.fields['password'].widget.attrs['placeholder'] = '비밀번호'


class CustomUserCreationForm(UserCreationForm):
    error_messages = {
        "password_mismatch": _("새로운 비밀번호가 일치하지 않습니다."),
    }

    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('nickname',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].label = ''
        self.fields['nickname'].label = ''
        self.fields['password1'].label = ''
        self.fields['password2'].label = ''
        self.fields['username'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['nickname'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['password1'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['password2'].widget.attrs['class'] = 'form-control mb-3 custom-form-input'
        self.fields['username'].widget.attrs['placeholder'] = '아이디'
        self.fields['nickname'].widget.attrs['placeholder'] = '닉네임'
        self.fields['password1'].widget.attrs['placeholder'] = '비밀번호'
        self.fields['password2'].widget.attrs['placeholder'] = '비밀번호 확인'
        
    def clean_username(self):
        """Reject usernames that differ only in case."""
        username = self.cleaned_data.get("username")
        if (
            username
            and self._meta.model.objects.filter(username__iexact=username).exists()
        ):
            self._update_errors(
                ValidationError(
                    {
                        "username": "이미 존재하는 아이디 입니다."
                        
                    }
                )
            )
        else:
            return username
        
class CustomReadOnlyPasswordHashWidget(ReadOnlyPasswordHashWidget) :
    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        summary = []
        if not value or value.startswith(UNUSABLE_PASSWORD_PREFIX):
            summary.append({"label": gettext("")})
        else:
            try:
                hasher = identify_hasher(value)
            except ValueError:
                summary.append(
                    {
                        "label": gettext(
                            "Invalid password format or unknown hashing algorithm."
                        )
                    }
                )
            else:
                for key, value_ in hasher.safe_summary(value).items():
                    summary.append({"label": gettext(key), "value": value_})
        context["summary"] = summary
        return context

class CustomReadOnlyPasswordHashField(ReadOnlyPasswordHashField) :
    widget = CustomReadOnlyPasswordHashWidget

class CustomUserChangeForm(UserChangeForm):  
    password = CustomReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=_(
            "Raw passwords are not stored, so there is no way to see this "
            "user’s password, but you can change the password using "
            '<a href="{}">this form</a>.'
        ),
    )

    class Meta:
        model = get_user_model()
        fields = (
            "nickname",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nickname'].label = ''
        self.fields['nickname'].help_text = ''
        self.fields['nickname'].widget.attrs['placeholder'] = '닉네임'
        self.fields['nickname'].widget.attrs['class'] = 'form-control custom-form-input'
        self.fields['password'].label = ''
        self.fields['password'].help_text = ''

class CustomPasswordChangeForm(PasswordChangeForm):
    error_messages = {
        "password_mismatch": _("새 비밀번호가 일치하지 않습니다."),
        "password_incorrect": _(
            "기존 비밀번호가 일치하지 않습니다."
        ),
    }
    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)
        self.fields['old_password'].label = ''
        self.fields['new_password1'].label = ''
        self.fields['new_password2'].label = ''
        self.fields['new_password1'].help_text = ''
        self.fields['old_password'].widget.attrs['placeholder'] = '기존 비밀번호'
        self.fields['new_password1'].widget.attrs['placeholder'] = '새 비밀번호'
        self.fields['new_password2'].widget.attrs['placeholder'] = '새 비밀번호 확인'
        self.fields['old_password'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['new_password1'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control mb-2 custom-form-input'

    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

class CustomMinimunMinimumLengthValidator(MinimumLengthValidator):
    def validate(self, password, user=None):
        if len(password) < self.min_length:
            raise ValidationError(
                ngettext(
                    "비밀번호가 너무 짧습니다. 비밀번호는 적어도 "
                    "%(min_length)d자 이상이어야 합니다.",
                    "비밀번호가 너무 짧습니다. 비밀번호는 적어도 "
                    "%(min_length)d자 이상이어야 합니다.",
                    self.min_length,
                ),
                code="password_too_short",
                params={"min_length": self.min_length},
            )

class CustomUserAttributeSimilarityValidator(UserAttributeSimilarityValidator) :
    def validate(self, password, user=None):
        if not user:
            return

        password = password.lower()
        for attribute_name in self.user_attributes:
            value = getattr(user, attribute_name, None)
            if not value or not isinstance(value, str):
                continue
            value_lower = value.lower()
            value_parts = re.split(r"\W+", value_lower) + [value_lower]
            for value_part in value_parts:
                if exceeds_maximum_length_ratio(
                    password, self.max_similarity, value_part
                ):
                    continue
                if (
                    SequenceMatcher(a=password, b=value_part).quick_ratio()
                    >= self.max_similarity
                ):
                    try:
                        verbose_name = str(
                            user._meta.get_field(attribute_name).verbose_name
                        )
                    except FieldDoesNotExist:
                        verbose_name = attribute_name
                    raise ValidationError(
                        _("비밀번호가 %(verbose_name)s와 유사합니다."),
                        code="password_too_similar",
                        params={"verbose_name": verbose_name},
                    )

class CustomCommonPasswordValidator(CommonPasswordValidator):
    def validate(self, password, user=None):
        if password.lower().strip() in self.passwords:
            raise ValidationError(
                _("비밀번호에 중복이 너무 많습니다.."),
                code="password_too_common",
            )
        
class CustomNumericPasswordValidator(NumericPasswordValidator):
    def validate(self, password, user=None):
        if password.isdigit():
            raise ValidationError(
                _("비밀번호는 숫자로 이루어질 수 없습니다."),
                code="password_entirely_numeric",
            )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, get_user_model
from .forms import CustomUserChangeForm, CustomUserCreationForm, CustomAuthenticationForm, CustomPasswordChangeForm
from django.views.decorators.http import require_POST, require_http_methods
from django.shortcuts import get_object_or_404
from datetime import datetime
from .models import User
import sys, os

sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))

from products.models import Article

def change_datetime(date_time_obj):
    date_obj = datetime.strptime(str(date_time_obj), "%Y-%m-%d %H:%M:%S.%f%z")
    return date_obj.strftime("%Y년 %m월 %d일")

def time_difference_in_words(time_str):
    input_time = datetime.strptime(str(time_str), "%Y-%m-%d %H:%M:%S.%f%z")
    now = datetime.now(input_time.tzinfo)
    time_diff = now - input_time
    minutes_diff = time_diff.total_seconds() / 60

    if minutes_diff < 10:
        return '방금'
    elif minutes_diff < 30:
        return '10분 전'
    elif minutes_diff < 60:
        return '30분 전'
    elif time_diff.days == 0:
        return f'{int(minutes_diff / 60)}시간 전'
    else:
        return f'{time_diff.days}일 전'

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == "POST":
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_path = request.GET.get('next') or 'products:home'
            return redirect(next_path)
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('products:home')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('products:home')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def profile(request, id):
    
    member = get_object_or_404(get_user_model(), id=id)
    articles = Article.objects.filter(author=member).order_by('-created_at')
    articles_id = [i.id for i in articles[:20]]
    articles_title = [i.title for i in articles[:20]]
    articles_created_at = [time_difference_in_words(i.created_at) for i in articles]
    
    like_count = Article.objects.filter(like_users=member).count()
    followers_count = User.objects.filter(followings=member).count()
    following_count = User.objects.filter(followers=member).count()
    context = {
        "member": member,
        "date_joined": change_datetime(member.date_joined),
        "articles": zip(articles_id, articles_title, articles_created_at),
        "like_count": like_count,
        "followers_count": followers_count,
        "following_count": following_count,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def update_profile(request):
    if request.method == "POST":
        form_password = CustomPasswordChangeForm(request.user, request.POST)
        form_name = CustomUserChangeForm(instance=request.user)
        if form_password.is_valid():
            form_password.save()
            update_session_auth_hash(request, form_password.user)
            return redirect('accounts:profile', request.user.id)
    else:
        form_password = CustomPasswordChangeForm(request.user)
        form_name = CustomUserChangeForm(instance=request.user)
    context = {
        'form_name': form_name,
        'form_password': form_password,
    }
    return render(request, 'accounts/update_profile.html', context)


@require_POST
def update_nickname(request):
    form_name = CustomUserChangeForm(request.POST, instance=request.user)
    if form_name.is_valid():
        form_name.save()
        return redirect('accounts:update_profile')

@require_POST
def follow(request, id):
    if request.user.is_authenticated:
        user = get_object_or_404(get_user_model(), id=id)
        if user != request.user :
            if user.followers.filter(id=request.user.id).exists() :
                user.followers.remove(request.user)
            else :
                user.followers.add(request.user)
        return redirect('accounts:profile', id = user.id)
    
    else :
        return redirect('accounts:login')
    

def like_article(request, id):
    member = get_object_or_404(get_user_model(), id=id)
    articles = Article.objects.filter(like_users=member).all()
    articles_id = [i.id for i in articles]
    articles_title = [i.title for i in articles]
    articles_created_at = [time_difference_in_words(i.created_at) for i in articles]
    context = {
        "member": member,
        "articles": zip(articles_id, articles_title, articles_created_at),
    }
    return render(request, 'accounts/like_articles.html', context)

accounts/templates/accounts/like_articles.html
{% extends "base.html" %}

{% block content %}
<div class="custom-body">
    <h1 class="mt-5 mb-2" style="font-size: 50px;">{{ member.nickname }} 의 찜목록</h1>

    <table class="table table-striped table-hover mt-5">
        <tbody>
            {% for id, title, created_at in articles %}
            <tr onclick="goToArticle('{{ id }}')">
                <th scope="row"></th>
                <td style="margin-left:10%; font-weight: 500;">{{ title }}</td>
                <td style="color: gray;">{{ created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    function goToArticle(articleId) {
        window.location.href = "../../../products/article/" + articleId;
    }
</script>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base_account.html" %}

{% block content %}
    <div class ="custom-body">
        <div class="d-flex justify-content-center">
            <div class="border border-2 rounded-1" style="margin-top: 10vw; --bs-border-opacity: .5;">
                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a class="custom-brand-logo navbar-brand" href="{% url 'products:home' %}">스파-마켓</a>
                </div>
                <form action="" class="custom-login-form" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <div class="d-grid gap-2 border-bottom" style="padding-bottom: 1vw;">
                        <input type="submit" class = "btn btn-primary" style="background-color: tomato; 
                        border: 0cap; font-weight: 600; font-size: 14px;"  value="로그인">
                    </div>
                    <div class="d-grid gap-2" style="padding-top: 1vw;">
                        <input type="button" onclick="goToSignup()" class = "btn btn-primary" style="background-color: white; 
                        border-color: tomato; font-weight: 600; color: tomato; font-size: 14px;" value="회원가입">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function goToSignup() {
            window.location.href = "../signup/"
        }
    </script>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div class="custom-body">
    <h1 class="mt-5 mb-2" style="font-size: 50px;">{{ member.nickname }}</h1>
    <p style="font-size: 20px; color: gray;"> {{ date_joined }}</p>

    <div class="container text-center" style="padding-left: 0;">
        <div class="row row-cols-auto">
            <div class="col" onclick="goToLikeArticles()">
                <p style="font-size: 20px; font-weight: 700;" >{{ like_count }}</p>
                <p style="font-size: 16px; font-weight: 400;">찜</p>
            </div>
            <div class="col">
                <p style="font-size: 20px; font-weight: 700;">{{ followers_count }}</p>
                <p style="font-size: 16px; font-weight: 400;">팔로워</p>
            </div>
            <div class="col">
                <p style="font-size: 20px; font-weight: 700;">{{ following_count}}</p>
                <p style="font-size: 16px; font-weight: 400;">팔로잉</p>
            </div>
        </div>
        <div class="row row-cols-4" style="font-size: 16px; font-weight: 400;">
        </div>
    </div>
    {% if request.user != member %}
    <form action="{% url 'accounts:follow' member.id %}" method="POST">
        {% csrf_token %}
        {% if request.user in member.followers.all %}
        <div class="d-grid gap-2">
            <button class="btn btn-primary" type="submit" style="background-color: white; 
            border-color: tomato; font-weight: 600; color: tomato;">팔로잉</button>
        </div>
        {% else %}
        <div class="d-grid gap-2">
            <button class="btn btn-primary" type="submit" style="background-color: tomato; 
            border: 0cap; font-weight: 600;">팔로우</button>
        </div>
        {% endif %}
    </form>
    {% else %}
    <div class="d-grid gap-2">
        <button class="btn btn-primary" type="button" style="background-color: tomato; 
            border: 0cap; font-weight: 600;" onclick="goToEdit()">정보 수정</button>
    </div>
    {% endif %}

    <table class="table table-striped table-hover mt-5">
        <tbody>
            {% for id, title, created_at in articles %}
            <tr onclick="goToArticle('{{ id }}')">
                <th scope="row"></th>
                <td style="margin-left:10%; font-weight: 500;">{{ title }}</td>
                <td style="color: gray;">{{ created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        function goToEdit() {
            window.location.href = "../../update_profile"
        }
        function goToArticle(articleId) {
            window.location.href = "../../../products/article/" + articleId;
        }
        function goToLikeArticles() {
            window.location.href = "../like_article";
        }
    </script>
    {% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base_account.html" %}

{% block content %}
    <div class ="custom-body">
        <div class="d-flex justify-content-center">
            <div class="border border-2 rounded-1" style="margin-top: 10vw; --bs-border-opacity: .5;">
                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a class="custom-brand-logo navbar-brand" href="{% url 'products:home' %}">스파-마켓</a>
                </div>
                <form action="{% url 'accounts:signup' %}" class="custom-login-form" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <div class="d-grid gap-2" style="padding-bottom: 1vw;">
                        <input type="submit" class = "btn btn-primary" style="background-color: tomato; 
                        border: 0cap; font-weight: 600; font-size: 14px;"  value="가입">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends "base.html" %}

{% block content %}
    <div class ="custom-body">
        <div class="d-flex justify-content-center">
            <div class="border border-2 rounded-1" style="margin-top: 10vw; --bs-border-opacity: .5;">
                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a class="custom-brand-logo navbar-brand" href="{% url 'products:home' %}">스파-마켓</a>
                </div>
                <form action="{% url 'accounts:update_nickname' %}" class="custom-login-form row g-2" method="POST">
                    {% csrf_token %}
                    <div class="col-auto">
                        {{ form_name }}
                    </div>
                    <div class="col-auto">
                        <input type="submit" class = "btn btn-primary mb-3" style="background-color: tomato; 
                        border: 0cap; font-weight: 600; font-size: 14px;"  value="닉네임 수정">
                    </div>
                </form>
                <form action="{% url 'accounts:update_profile' %}" class="custom-login-form" method="POST">
                    {% csrf_token %}
                    {{ form_password }}
                    <div class="d-grid gap-2" style="padding-bottom: 1vw;">
                        <input type="submit" class = "btn btn-primary" style="background-color: tomato; 
                        border: 0cap; font-weight: 600; font-size: 14px;"  value="저장">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}