accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("<int:id>/profile/", views.profile, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path("update_nickname/", views.update_nickname, name="update_nickname"),
    path("<int:id>/follow/", views.follow, name="follow"),
    path('<int:id>/like_article/', views.like_article, name='like_article'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('article/<int:id>/', views.article, name='article'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('<int:id>/like/', views.like, name='like'),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.conf import settings

class Article(models.Model):
    title = models.CharField(max_length=50, blank=False)
    content = models.TextField(blank=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = "articles")
    image = models.ImageField(upload_to='images/', blank=True)
    price = models.IntegerField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = "like_articles")
    def __str__(self):
        return self.title
    

products/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ("author","like_users")

products/views.py
from datetime import datetime
from .forms import ArticleForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from .models import Article


def time_difference_in_words(time_str):
    input_time = datetime.strptime(time_str, "%Y-%m-%d %H:%M:%S.%f%z")
    now = datetime.now(input_time.tzinfo)
    time_diff = now - input_time
    minutes_diff = time_diff.total_seconds() / 60

    if minutes_diff < 10:
        return '방금'
    elif minutes_diff < 30:
        return '10분 전'
    elif minutes_diff < 60:
        return '30분 전'
    elif time_diff.days == 0:
        return f'{int(minutes_diff / 60)}시간 전'
    else:
        return f'{time_diff.days}일 전'

def format_price(price):
    if price >= 10000:
        return f"{round(price / 10000)}만원"
    elif price >= 1000:
        thousands = round(price / 1000)
        if thousands >= 10:
            return f"{thousands}천원"
        else:
            hundreds = round((price % 10000) / 100)
            return f"{thousands}천 {hundreds}백원"
    else:
        return f"{price}원"

def home(request):
    articles = Article.objects.all()
    for article in articles :
        article.price = format_price(article.price) 
    context = {"articles": articles}
    return render(request, 'products/home.html', context)


def article(request, id):
    article = get_object_or_404(Article, id=id)
    article_time = time_difference_in_words(str(article.created_at))
    context = {
        "article": article,
        "article_time": article_time,
    }
    return render(request, 'products/article.html', context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect("products:article", article.id)
        context = {"form": form}
        return render(request, 'products/create.html', context)
    else:
        form = ArticleForm()
    context = {"form": form}
    return render(request, 'products/create.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def edit(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect("products:article", article.id)
    else:
        form = ArticleForm(instance=article)
    context = {
        "form": form,
        "article": article,
    }
    return render(request, 'products/edit.html', context)


@require_POST
def delete(request, id):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, id=id)
        if request.method == "POST":
            article.image.delete()
            article.delete()
            return redirect("products:home")
        context = {"article": article}
        return render(request, 'products/delete.html', context)


@require_POST
def like(request, id):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, id=id)
        if article.like_users.filter(id=request.user.id).exists():
            article.like_users.remove(request.user)
        else:
            article.like_users.add(request.user)
        return redirect("products:article", article.id)
    return redirect("accounts:login")

products/templates/products/article.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="custom-body">
    <div class="mb-5">

    </div>

    {% if article.image %}
    <img class="rounded mx-auto d-block" src="{{ article.image.url }}"><br>
    {% endif %}
    
    <div class = "border-bottom" onclick="goToProfile('{{ article.author.id }}')" style="font-size: 17px; margin-top:20px; margin-bottom: 20px; padding-bottom: 20px; font-weight: 500;">{{ article.author.nickname }}</div>

    <div class = "border-bottom" style="margin-top:20px; margin-bottom: 20px; padding-bottom:20px">
        <h1 style="font-size: 20px; font-weight: 800;" >{{ article.title }}</h1>
        <p style="font-size: 18px; font-weight: 500;">{{ article.price }} 원</p>
        <p>{{ article.content }}</p>
        <p>{{ article_time }}</p>
    </div>
    
    <div class="d-flex justify-content-between">
        <form id="like-form" action="{% url 'products:like' article.id %}" method="POST">
            {% csrf_token %}
            {% if request.user in article.like_users.all %}
                <img src='{% static "products/un_like.png"%}' onclick="submitForm(event, 'like-form')">    
            {% else %}
                <img src='{% static "products/like.png"%}' onclick="submitForm(event, 'like-form')">
            {% endif %}
        </form>
        <div class="d-flex" style="font-size: small; color: darkgray;">
            {% if request.user == article.author %}
                <p onclick="goToEdit('{{ article.id }}')">수정</p>      
                <form id="delete-form" action="{% url 'products:delete' article.id %}" method="POST">
                    {% csrf_token %}
                    <p onclick = "submitForm(event, 'delete-form')" style="margin-left: 15px;">삭제</p>
                </form>
            {% endif %}
        </div>
    </div>
    
    

</div>

<script>
    function goToProfile(author) {
        window.location.href = "../../../accounts/"+author+"/profile/";
    }
    function goToEdit(articleID) {
        window.location.href = "../../edit/"+articleID;
    }
    function submitForm(event, formID) {
        event.preventDefault();
        var form = document.getElementById(formID);
            form.submit();
    }
</script>
    
{% endblock content %}

products/templates/products/create.html
{% extends "base.html" %}

{% block content %}
<div class="custom-body">
    <form id="form" action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-5 mt-5">
            <h3>물품 등록</h3>
        </div>
        <div class="mb-3">
            <input class="form-control form-control-lg" placeholder="물품" id="title" name="title" rows="1"
                style="font-weight: 500;">
        </div>
        <div class="mb-3">
            <textarea class="form-control" placeholder="물품에 대한 설명을 적어주세요" id="content" name="content"
                rows="10"></textarea>
        </div>
        <div class="row g-3 align-items-center mb-3">
            <div class="col-auto">
                <input type="number" name="price" placeholder="가격" id="price" class="form-control"
                    value="{{ form.price.value }}">
            </div>
        </div>
        <div class="mb-3">
            <input class="form-control" type="file" name="image">
        </div>
        <div class="d-flex justify-content-end">
            <button class="btn btn-outline-danger" type="button" onclick="ifEmpty(event)">등록</button>
        </div>
    </form>
</div>

<script>
    function ifEmpty(event) {
        event.preventDefault();
        if (document.getElementById("title").value == "" || document.getElementById("content").value == "" ||
            document.getElementById("price").value == "") {
            swal('등록 실패', "필수 항목을 모두 입력해주세요", 'warning')
        } else {
            document.getElementById("form").submit();
        }
    }
</script>
{% endblock content %}

products/templates/products/edit.html
{% extends "base.html" %}

{% block content %}
<div class="custom-body">
    <form id="form" action="{% url 'products:edit' article.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-5 mt-5">
            <h3>물품 등록</h3>
        </div>
        <div class="mb-3">
            <input class="form-control form-control-lg" placeholder="물품" id="title" name="title" rows="1"
                style="font-weight: 500;" value="{{ form.title.value }}">
        </div>
        <div class="mb-3">
            <textarea class="form-control" placeholder="물품에 대한 설명을 적어주세요" id="content" name="content"
                rows="10">{{ form.content.value }}</textarea>
        </div>
        <div class="row g-3 align-items-center mb-3">
            <div class="col-auto">
                <input type="number" name="price" placeholder="가격" id="price" class="form-control"
                    value="{{ form.price.value }}">
            </div>
        </div>
        <div class="mb-3">
            <input class="form-control" type="file" name="image" value=""></input>
        </div>
        <div class="d-flex justify-content-end">
            <button class="btn btn-outline-danger" type="button" onclick="ifEmpty(event)">수정</button>
        </div>
    </form>
</div>

<script>
    function ifEmpty(event) {
        event.preventDefault();
        if (document.getElementById("title").value == "" || document.getElementById("content").value == "" ||
            document.getElementById("price").value == "") {
            swal('등록 실패', "필수 항목을 모두 입력해주세요", 'warning')
        } else {
        document.getElementById("form").submit();
    }
    }
</script>
{% endblock content %}

products/templates/products/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="home-div">
    <h1>스파르타 마켓</h1>
    <p>우리들을 위한 중고거래</p>
</div>
<div class="row row-cols-1 row-cols-md-4 g-4 custom-body">
    {% for article in articles %}
    <div class="col" onclick="goToArticle('{{ article.id }}')">
        <div class="card h-100 rounded-4" style="overflow: hidden">
            {% if article.image %}
            <img src="{{ article.image.url }} " style="width: 240px; height: 160px; object-fit: cover;" class="img-fluid rounded-4" alt='{% static "products/noimage.png"%}'>
            {% else %}
            <img src='{% static "products/noimage.png"%}' class="img-fluid rounded-5" alt="">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title">{{ article.title }}</h4> <br>
                <div class="card-text">{{ article.price }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script>
    function goToArticle(articleId) {
        window.location.href = "article/" + articleId;
    }
</script>


{% endblock content %}